# Generated by Django 3.2.9 on 2021-12-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzdevumi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='math',
            field=models.IntegerField(),
        ),
    ]
